name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.6-alpine
      options: --privileged

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add --no-cache \
            build-base \
            ccache \
            git \
            ncurses5-libs \
            libstdc++ \
            openjdk8-jre \
            unzip \
            zlib-dev \
            libltdl \
            libffi-dev \
            openssl-dev \
            autoconf \
            automake
          apk add --no-cache py-pip
          pip install --upgrade pip
          pip install --upgrade cython==0.29.19
          pip install --upgrade buildozer
      - name: Build APK
        run: |
          buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
